#!/bin/bash

IPT='/sbin/iptables'
GREP=`which grep`
AWK=`which awk`
EXPR='/usr/bin/expr'
WC='/usr/bin/wc'

STAT=0
OUTPUT='IPTABLES '
CHAINS=`$IPT -nvL | $GREP 'Chain' | $AWK '{ print $2 }'`

for CHAIN in $CHAINS ; do
        if [ "$CHAIN" != 'FORWARD' ] && [ "$CHAIN" != 'OUTPUT' ] && [ `$EXPR substr $CHAIN 1 4` != "LOG_" ] ; then
                CNT=`expr $($IPT -S $CHAIN | $WC -l) '-' 1`
                if [ $CNT -eq 0 ] ; then
                        OUTPUT="${OUTPUT}ERROR  $CHAIN $CNT rules! "
                        STAT=2
                else
                        OUTPUT="${OUTPUT}OK [ $CHAIN $CNT rules ] "
                fi
        fi
done

echo $OUTPUT

exit $STAT
